'\" t
.TH "GCLOUD\-COMPUTE\-TARGET\-POOLS\-GET\-HEALTH" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-target-pools-get-health \- Get the health of instances in a target pool
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute target\-pools get\-health\fR
  NAME
  [\-\-fields FIELDS [FIELDS \&...]]
  [\-\-help]
  [\-\-limit LIMIT]
  [\-\-region REGION]
  [\-\-sort\-by SORT_BY]
  [\-h]
.fi
.SH "DESCRIPTION"
.sp
\fBgcloud compute target\-pools get\-health\fR displays the health of instances in a target pool\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the target pool\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-fields\fR \fIFIELDS [FIELDS \&...]\fR
.RS 4
Fields to display\&. Possible values are:
.sp
.if n \{\
.RS 4
.\}
.nf
healthStatus[]\&.healthState
healthStatus[]\&.instance
healthStatus[]\&.ipAddress
kind
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-limit\fR \fILIMIT\fR
.RS 4
The maximum number of results\&.
.RE
.PP
\fB\-\-region\fR \fIREGION\fR
.RS 4
The region of the target pool to get health information for\&. If omitted and the arguments are not all URIs, you will be prompted to select a region\&.
.RE
.PP
\fB\-\-sort\-by\fR \fISORT_BY\fR
.RS 4
A field to sort by\&. To perform a descending\-order sort, prefix the value of this flag with a tilde (\(lq~\(rq)\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
